#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

// Colors for console output
const colors = {
    reset: '\x1b[0m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    red: '\x1b[31m',
    blue: '\x1b[34m',
    cyan: '\x1b[36m'
};

function log(message, color = colors.reset) {
    console.log(`${color}${message}${colors.reset}`);
}

function executeCommand(command, description) {
    try {
        log(`\n▶ ${description}...`, colors.cyan);
        execSync(command, { stdio: 'inherit' });
        log(`✅ ${description} completed successfully!`, colors.green);
        return true;
    } catch (error) {
        log(`❌ Failed to ${description.toLowerCase()}`, colors.red);
        log(`Error: ${error.message}`, colors.red);
        return false;
    }
}

function getCurrentProjectName() {
    return path.basename(process.cwd());
}

function checkGitInstalled() {
    try {
        execSync('git --version', { stdio: 'ignore' });
        return true;
    } catch (error) {
        return false;
    }
}

function checkIfGitRepo() {
    try {
        execSync('git rev-parse --git-dir', { stdio: 'ignore' });
        return true;
    } catch (error) {
        return false;
    }
}

function getRemoteUrl(projectName) {
    return `https://github.com/amatak-cloud/${projectName}.git`;
}

function promptUser(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer);
        });
    });
}

async function createGitIgnore() {
    const gitIgnorePath = path.join(process.cwd(), '.gitignore');
    
    if (!fs.existsSync(gitIgnorePath)) {
        log('\nCreating .gitignore file...', colors.yellow);
        
        const defaultGitIgnore = `# Dependencies
node_modules/
.pnp/
.pnp.js
.yarn/install-state.gz

# Testing
coverage/
.nyc_output/

# Production
build/
dist/
out/

# Misc
.DS_Store
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
.project
.classpath
.settings/

# Logs
logs/
*.log

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build output
.nuxt

# Gatsby build output
public

# Vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
env.bak/
venv.bak/
pythonenv*/

# Java
*.class
*.jar
*.war
*.ear
hs_err_pid*
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
!/.mvn/wrapper/maven-wrapper.jar

# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out

# Rust
/target/
**/*.rs.bk
Cargo.lock

# Ruby
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/
*.bundle
*.so
*.o
*.a
mkmf.log
*.orig
Gemfile.lock
.yardoc
_yardoc
doc/
.rdoc

# Swift
*.xcodeproj/
*.xcworkspace/
*.pbxuser
*.mode1v3
*.mode2v3
*.perspectivev3
*.xcuserstate
*.xcuserdatad
.xcshareddata/
.xcscmblueprint
DerivedData/
build/
*.hmap
*.ipa
*.dSYM.zip
*.dSYM
timing.h
*.moved-aside
!default.pbxuser
!default.mode1v3
!default.mode2v3
!default.perspectivev3

# PHP
composer.phar
/vendor/
/.idea/
/.php_cs
/.php_cs.cache
/.phpunit.result.cache
Thumbs.db
*.log

# WordPress
wp-content/uploads/
wp-content/cache/
wp-content/upgrade/
*.sql
*.tar
*.zip
.htaccess
wp-config-local.php
wp-config.dev.php
wp-config.staging.php
wp-config.production.php

# Laravel
/node_modules/
/public/storage
/storage/*.key
/vendor/
.env
.env.backup
.phpunit.result.cache
Homestead.json
Homestead.yaml
npm-debug.log
yarn-error.log
/.idea/
/.vscode/

# React Native
node_modules/
npm-debug.log
yarn-debug.log
yarn-error.log
.watchmanconfig
*.log
build/
android/app/build/
ios/build/
ios/Pods/
*.xcworkspace/
*.xcodeproj/
project.xcworkspace/
xcuserdata/
*.pbxuser
*.mode1v3
*.mode2v3
*.perspectivev3
*.xcuserstate
*.xccheckout
*.moved-aside
DerivedData/
*.hmap
*.ipa
*.dSYM.zip
*.dSYM
timing.h
*.class
*.apk
*.a
*.o
*.dylib
*.so
*.lib
*.exp
*.ilk
*.pdb
*.dll
*.exe
*.obj
*.jar
*.war
*.ear
*.tar.gz
*.tgz
*.zip
*.7z
*.rar
Thumbs.db
.DS_Store
`;
        
        fs.writeFileSync(gitIgnorePath, defaultGitIgnore);
        log('✅ .gitignore file created', colors.green);
    } else {
        log('\n.gitignore file already exists, skipping...', colors.yellow);
    }
}

async function main() {
    log('\n🚀 Git Repository Initialization Script', colors.blue);
    log('======================================\n', colors.blue);
    
    // Check if git is installed
    if (!checkGitInstalled()) {
        log('❌ Git is not installed. Please install git first.', colors.red);
        process.exit(1);
    }
    
    const projectName = getCurrentProjectName();
    log(`📁 Current Project: ${projectName}`, colors.cyan);
    
    // Check if already a git repository
    const isGitRepo = checkIfGitRepo();
    if (isGitRepo) {
        log('⚠️  This directory is already a git repository!', colors.yellow);
        const answer = await promptUser('Do you want to reinitialize? (y/N): ');
        if (answer.toLowerCase() !== 'y') {
            log('❌ Operation cancelled', colors.red);
            rl.close();
            return;
        }
        
        // Remove existing git
        try {
            fs.rmSync('.git', { recursive: true, force: true });
            log('✅ Removed existing git repository', colors.green);
        } catch (error) {
            log('❌ Failed to remove existing git repository', colors.red);
            rl.close();
            return;
        }
    }
    
    // Confirm repository name
    log(`\n📦 Repository will be created as: ${colors.yellow}amatak-cloud/${projectName}${colors.reset}`);
    const confirm = await promptUser('Is this correct? (Y/n): ');
    
    let finalProjectName = projectName;
    if (confirm.toLowerCase() === 'n') {
        finalProjectName = await promptUser('Enter repository name: ');
    }
    
    // Create .gitignore
    await createGitIgnore();
    
    // Execute git commands
    log('\n🚀 Executing git commands...', colors.blue);
    
    const commands = [
        { cmd: 'git init', desc: 'Git init' },
        { cmd: 'git add .', desc: 'Git add' },
        { cmd: 'git commit -m "first commit"', desc: 'Git commit' },
        { cmd: 'git branch -M main', desc: 'Rename branch to main' },
        { cmd: `git remote add origin https://github.com/amatak-cloud/${finalProjectName}.git`, desc: 'Add remote origin' }
    ];
    
    for (const command of commands) {
        const success = executeCommand(command.cmd, command.desc);
        if (!success) {
            log('\n❌ Git initialization failed!', colors.red);
            rl.close();
            return;
        }
    }
    
    // Ask about push
    log('\n', colors.reset);
    const pushAnswer = await promptUser('Do you want to push to remote now? (Y/n): ');
    
    if (pushAnswer.toLowerCase() !== 'n') {
        const pushSuccess = executeCommand('git push -u origin main', 'Git push');
        if (pushSuccess) {
            log('\n✅ Repository successfully initialized and pushed!', colors.green);
            log(`🔗 Remote URL: https://github.com/amatak-cloud/${finalProjectName}.git`, colors.cyan);
        }
    } else {
        log('\n✅ Repository initialized locally. Push manually with:', colors.yellow);
        log('   git push -u origin main', colors.cyan);
    }
    
    // Show status
    log('\n📊 Current Git Status:', colors.blue);
    try {
        execSync('git status', { stdio: 'inherit' });
    } catch (error) {
        // Ignore status errors
    }
    
    log('\n✨ Git initialization complete!', colors.green);
    rl.close();
}

// Handle Ctrl+C
process.on('SIGINT', () => {
    log('\n\n❌ Operation cancelled by user', colors.red);
    rl.close();
    process.exit(0);
});

// Run the script
if (require.main === module) {
    main().catch(error => {
        log(`\n❌ Unexpected error: ${error.message}`, colors.red);
        rl.close();
        process.exit(1);
    });
}

module.exports = { main };